# 固定名のブランチ app-icons に、1536x1536(px)のPNG画像ファイル
#  - app_icon_sources/app_icon_background.png
#  - app_icon_sources/app_icon_foreground.png
# 上記２ファイル（片方でもOK）をpushすると、
# それらを使った iOS + Android アプリ用アイコン画像リソースファイル一式を
# app_icons/ ディレクトリにコミットして、masterへのプルリクエストを発行します。

name: App用アイコン画像セット生成

# Controls when the workflow will run
on:
  push:
    branches:
      - master
    paths:
      - app_icon_sources/app_icon_background.png
      - app_icon_sources/app_icon_foreground.png

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      # Setting an environment variable with the value of a configuration variable
      #env_var: ${{ vars.ENV_CONTEXT_VAR }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install fuse
          mkdir -p "$HOME/.local/bin"
          curl -O 'https://download.imagemagick.org/archive/binaries/magick'
          chmod u+x magick
          mv magick "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Generate Image resources for App-Icon
        run: |
          if [[ $(identify -format "%[width],%[height]\n" ./app_icon_sources/app_icon_background.png) == "1536,1536" 
          && $(identify -format "%[width],%[height]\n" ./app_icon_sources/app_icon_foreground.png) == ""1536,1536 ]]; then
            git switch -c app-icons
            git ls-remote --heads --exit-code origin "$(git symbolic-ref --short HEAD)"
            if [ $? -eq 0 ]; then
              git push origin --delete app-icons
            fi
            mkdir -p "$HOME/workdir"
            sh ./scripts/makeIcons.sh ./app_icon_sources/app_icon_background.png ./app_icon_sources/app_icon_foreground.png $HOME/workdir
            cp -r -f "$HOME/workdir/app_icons" .
          else
            echo "Invalid image size!"
            exit 1
          fi

      - name: Add and commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./app_icons
          git commit -m "Appアイコン更新"
          git push origin app-icons

      - name: Create Pull request
        run: |
          gh pr create -B master -t "Appアイコン更新" -b "アプリ用アイコン画像リソースファイル一式（自動生成）"
