# This is a basic workflow to help you get started with Actions

name: App用アイコン画像セット生成

# Controls when the workflow will run
on:
  push:
    branches:
      - master
    paths:
      - Sources/Icon_background.png
      - Sources/Icon_foreground.png

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install fuse
          mkdir -p "$HOME/.local/bin"
          curl -O 'https://download.imagemagick.org/archive/binaries/magick'
          chmod u+x magick
          mv magick "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Check
        id: checkImageSize
        run: |
          identify -format "bg_image_size=%[width],%[height]" ./Sources/Icon_background.png >> $GITHUB_OUTPUT
          identify -format "fg_image_size=%[width],%[height]" ./Sources/Icon_foreground.png >> $GITHUB_OUTPUT

      - name: Error
        if: ${{steps.checkImageSize.outputs.bg_image_size != '1536,1536' || steps.checkImageSize.outputs.fg_image_size != '1536,1536'}}
        run: echo "Invalid image size!"

      - name: Convert
        if: ${{steps.checkImageSize.outputs.bg_image_size == '1536,1536' && steps.checkImageSize.outputs.fg_image_size == '1536,1536'}}
        run: |
          mkdir -p "$HOME/workdir"
          sh ./Scripts/makeIcons.sh ./Sources/Icon_background.png ./Sources/Icon_foreground.png $HOME/workdir
          ls $HOME/workdir/AppIcons/Android/drawable-hdpi
