# This is a basic workflow to help you get started with Actions

name: App用アイコン画像セット生成

# Controls when the workflow will run
on:
  push:
    branches:
      - app-icons
    paths:
      - Sources/Icon_background.png
      - Sources/Icon_foreground.png

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      # Setting an environment variable with the value of a configuration variable
      env_var: ${{ vars.ENV_CONTEXT_VAR }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: app-icons

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install fuse
          mkdir -p "$HOME/.local/bin"
          curl -O 'https://download.imagemagick.org/archive/binaries/magick'
          chmod u+x magick
          mv magick "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Generate Image resources for App-Icon
        run: |
          if [[ $(identify -format "%[width],%[height]\n" ./Sources/Icon_background.png) == "1536,1536" 
          && $(identify -format "%[width],%[height]\n" ./Sources/Icon_background.png) == ""1536,1536 ]]; then
            mkdir -p "$HOME/workdir"
            sh ./Scripts/makeIcons.sh ./Sources/Icon_background.png ./Sources/Icon_foreground.png $HOME/workdir
            cp -r -f "$HOME/workdir/AppIcons" .
            ls ./AppIcons/iOS
          else
            echo "Invalid image size!"
            exit 1
          fi

      - name: Add and commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./AppIcons
          git commit -m "Update App Icons"
          git push origin app-icons

      - name: Create Pull request
        run: |
          gh pr create -B master -t "アイコン画像更新" -b "アプリ用アイコン画像リソースファイル一式（自動生成）"
