# This is a basic workflow to help you get started with Actions

name: App用アイコン画像セット生成

# Controls when the workflow will run
on:
  push:
    branches:
      - master
    paths:
      - Sources/Icon_background.png
      - Sources/Icon_foreground.png

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run identify command
        run: identify
        id: identify_output

      - name: Check for "Hoge" string
        run: |
          if [[ "${{ steps.identify_output.stdout }}" == *"Hoge"* ]]; then
            echo "Hoge string found"
            sh huga.sh
          else
            echo "Hoge string not found"
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install fuse
          mkdir -p "$HOME/.local/bin"
          curl -O 'https://download.imagemagick.org/archive/binaries/magick'
          chmod u+x magick
          mv magick "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Get image size
        id: get_image_size
        run: |
          echo "background_image_size=${{identify -format "%[width],%[height]" ./Sources/Icon_background.png}}" >> $GITHUB_OUTPUT
          echo "foreground_image_size=${{identify -format "%[width],%[height]" ./Sources/Icon_foreground.png}}" >> $GITHUB_OUTPUT

      - name: Check image size
        run: |
          if [[ "${{ steps.get_image_size.background_image_size }}" == '1536,1536' && "${{ steps.get_image_size.foreground_image_size }}" == '1536,1536' ]]; then
            mkdir -p "$HOME/workdir"
            sh ./Scripts/makeIcons.sh ./Sources/Icon_background.png ./Sources/Icon_foreground.png $HOME/workdir
            ls $HOME/workdir/AppIcons/Android/drawable-hdpi
          else
            echo "Invalid image size!"
          fi
